### Load in NumPy (remember to pip install numpy first)

In [58]:
import numpy as np

### The Basics

In [59]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [60]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [61]:
# Get Dimension
a.ndim
b.ndim

2

In [62]:
# Get Shape
b.shape

(2, 3)

In [63]:
# Get Type
a.dtype

dtype('int32')

In [64]:
# Get Size
a.itemsize

4

In [65]:
# Get total size
a.nbytes

12

In [66]:
# Get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [67]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [68]:
# Get a specific element [r, c]
a[1, 5]

13

In [69]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [70]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [71]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [72]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [73]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [74]:
# Get specific element (work outside in)
b[0,1,1]

4

In [75]:
# replace 
b[:,1,:] = [[9,9],[8,8]]

In [76]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [77]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [79]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [80]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [81]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.26361327, 0.33933209],
       [0.52785245, 0.08677652],
       [0.87938284, 0.33173425],
       [0.57688707, 0.28540947]])

In [82]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-3,  2,  6],
       [ 6, -4, -4],
       [ 7, -2,  5]])

In [83]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [84]:
# Repeat an array (read)
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [85]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [86]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [87]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [88]:
a + 2

array([3, 4, 5, 6])

In [89]:
a - 2

array([-1,  0,  1,  2])

In [90]:
a * 2

array([2, 4, 6, 8])

In [91]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [92]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [93]:
a ** 2

array([ 1,  4,  9, 16])

In [94]:
# Take the sin
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [95]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

##### Linear Algebra

In [96]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [97]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [98]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

##### Statistics

In [99]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
# np.min(stats, axis=0)
np.min(stats)

1

In [101]:
np.max(stats, axis=1)

array([3, 6])

In [102]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [103]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [104]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [106]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [107]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [108]:
(filedata<0)

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])